name: nerthus2
env: example
vars:
  certificate_arn: arn:aws:acm:ap-northeast-1:217183500018:certificate/31f4a295-84f3-46b2-b9a6-96100d474e46
  ami: ami-0bba69335379e17f8
  instance_size: t3.micro
  cidr_base: 10.200.0
  zone: nerthus2.example.infra
  visuale_host: visuale.cantara.no
  service_tag: Nerthus2 Example
services:
  - name: nerthus
    git: github.com/Cantara/nerthus2
    branch: main
    vars:
      webserver_port: 13030
  - name: wamper
    number_of_nodes: 2
    git: github.com/Cantara/wamper
    branch: main
    vars:
      webserver_port: 13030
    override: #Overrides dependencies
      eventstore: services/eventstore #In this case overrides local installation with deployed service
  - name: visuale
    local: visuale.yml
    git: github.com/Cantara/visuale
    branch: master
    number_of_nodes: 1
    vars:
      webserver_port: 9292
      access_token: 65971cb8-54af-42b4-8853-30989764ed5a