name: Set local_override properties
dependencies:
  - role: user
vars:
  service:
  properties_name:
  local_override_content:
tasks:
  - name: Set properties file
    copy:
      content: "{{ local_override_content }}"
      dest: "~/{{ properties_name }}"
      mode: 0640
    become: yes
    become_user: "{{ service }}"