name: Set service CRON
dependencies:
  - role: user
  - role: buri
vars:
  service:
  artifact_group:
  webserver_port:
  env:
  visuale_host:
  service_tag:
  service_type:
  health_type:
  hostname:
  is_frontend: false
tasks:
  - set_fact:
      visuale: "https://{{ visuale_host }}/api/status/{{ env }}/{{ service | capitalize }}/{{ hostname }}?service_tag={{ service_tag }}&service_type={{ service_type }}"
  - block:
    - name: Set service cron file
      copy:
        content: |
          MAILTO=""
          */6 * * * * ./buri -t go -a buri -g no/cantara/gotools > /dev/null
          */6 * * * * ./buri -t go -a nerthus2/probe/health -g no/cantara/gotools > /dev/null
          */6 * * * * ./buri -t {{ health_type }} -a {{ service }} -g {{ artifact_group }} -r > /dev/null
          */5 * * * * ./nerthus2-probe-health -d 5m -r "{{ visuale }}" -h "http://localhost:{{ webserver_port }}/{{ service }}/health" -a "{{ service }}" -t "{{ health_type }}" {{ '-b' if is_frontend }} > /dev/null &
        dest: "/home/{{ service }}/CRON"
        mode: 0640
      register: service_cron
    - name: Remove cronjob from crontab scheduler
      shell: crontab -r
      ignore_errors: true
      when: service_cron is changed
    - name: Configure cronjob via crontab scheduler
      shell: "crontab /home/{{ service }}/CRON"
      when: service_cron is changed
    become: yes
    become_user: "{{ service }}"