name: Set files
dependencies:
  - role: user
vars:
  service:
  files:
tasks:
  - block:
      - name: create directory if they don't exist
        file:
          path: "~/{{ item }}"
          state: directory
          mode: '0750'
        with_items: "{{ dirs }}"
        when: dirs is defined
      - name: "Set files"
        copy:
          content: "{{ item.content | string }}"
          dest: "~/{{ item.name }}"
          mode: "{{ item.mode }}" #0640
        with_items: "{{ files }}"
    become: yes
    become_user: "{{ service }}"