name: Set files
dependencies:
  - role: user
vars:
  service:
  files:
tasks:
  - name: "Set files"
    copy:
      content: "{{ item.content | string }}"
      dest: "~/{{ item.name }}"
      mode: 0640
    with_items: "{{ files }}"
    become: yes
    become_user: "{{ service }}"