name: Add service
dependencies:
  - role: utf8
  - role: user
  - role: buri
  - role: cron
  - role: service_cron
vars:
  service:
  service_exec:
tasks:
  - name: Start service
    shell: "cd ~ && {{ service_exec }}"
    when: service_exec is defined
    become: yes
    become_user: "{{ service }}"