name: Install Zulu repo
tasks:
  - name: Install Zulu repo
    ansible.builtin.yum:
      name: https://cdn.azul.com/zulu/bin/zulu-repo-1.0.0-1.noarch.rpm
      state: present
    become: yes
    become_user: root