name: Set docker credentials
dependencies:
  - role: docker
vars:
  service:
  docker_username: missing
  docker_password: missing
  docker_host: docker.greps.dev
tasks:
  - name: "Add docker group to {{ service }}"
    ansible.builtin.user:
      name: "{{ service }}"
      groups: docker
      append: yes
    become: yes
    become_user: root
  - name: Installing requests module
    ansible.builtin.shell: |
      yes | pip3 install requests --quiet --exists-action i
  - name: Log into private registry and force re-authorization
    community.docker.docker_login:
      registry_url: "{{ docker_host }}"
      username: "{{ docker_username }}"
      password: "{{ docker_password }}"
      reauthorize: true
  - block:
    - name: Installing requests module
      ansible.builtin.shell: |
        yes | pip3 install requests --quiet --exists-action i
    - name: Log into private registry and force re-authorization
      community.docker.docker_login:
        registry_url: "{{ docker_host }}"
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        reauthorize: true
    become: yes
    become_user: "{{ service }}"