name: Setup Mongodb
dependencies:
  - role: docker
  - role: docker_credentials
  - role: service
vars:
  tag: ":3.4.2-g2"
  env: dev
  version: 22.11.2-SNAPSHOT
  mongo_host_port: 27017
  mongo_container_port: 27017
  service:
  service_in_docker: true
tasks:
  - name: Create gradle directory if it does not exist
    become: yes
    become_user: "{{ service }}"
    ansible.builtin.file:
      path: "~/mongodb"
      state: directory
      mode: '0750'
  - name: Create a Mongodb container
    become: yes
    become_user: "{{ service }}"
    community.docker.docker_container:
      name: mongodb
      user: "{{ service_user.uid }}:{{ service_user.group }}"
      image: "docker.greps.dev/mongodb3{{ tag }}"
      pull: true
      volumes:
        - "~/mongodb:/usr/mongodb/data"
        - "/var/log/mongodb:/usr/mongodb/logs"
      restart_policy: always
      ports:
        - "{{ mongo_host_port }}:{{ mongo_container_port }}"
      env:
        GREPS_ENV: "{{ env }}"
        GREPS_VERSION: "{{ version }}"
        DOCKER_USER: "$(id -u):$(id -g)"