name: Install Nexus
dependencies:
  - role: java_8
  - role: user
tasks:
  - block:
    - name: Download Nexus
      ansible.builtin.get_url:
        url: "https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/3/nexus-3.29.2-02-unix.tar.gz"
        dest: "/tmp/nexus-3.29.2-02-unix.tar.gz"
    - name: Extract nexus into home
      ansible.builtin.unarchive:
        src: /tmp/nexus-3.29.2-02-unix.tar.gz
        dest: "/home/{{ service }}"
        owner: nexus
        group: nexus
        extra_opts:
        - --strip-components=1
    - name: Set vmoptions
      copy:
        content: |
          -Xms1024m
          -Xmx1024m
          -XX:MaxDirectMemorySize=1024m
  
          -XX:LogFile=./sonatype-work/nexus3/log/jvm.log
          -XX:-OmitStackTraceInFastThrow
          -Djava.net.preferIPv4Stack=true
          -Dkaraf.home=.
          -Dkaraf.base=.
          -Dkaraf.etc=etc/karaf
          -Djava.util.logging.config.file=/etc/karaf/java.util.logging.properties
          -Dkaraf.data=./sonatype-work/nexus3
          -Dkaraf.log=./sonatype-work/nexus3/log
          -Djava.io.tmpdir=./sonatype-work/nexus3/tmp
          -XX:+UnlockDiagnosticVMOptions
          -XX:+LogVMOutput
          -Dkaraf.startLocalConsole=false
          #
          # additional vmoptions needed for Java9+
          #
          # --add-reads=java.xml=java.logging
          # --add-exports=java.base/org.apache.karaf.specs.locator=java.xml,ALL-UNNAMED
          # --patch-module=java.base=lib/endorsed/org.apache.karaf.specs.locator-4.2.9.jar
          # --patch-module=java.xml=lib/endorsed/org.apache.karaf.specs.java.xml-4.2.9.jar
          # --add-opens=java.base/java.security=ALL-UNNAMED
          # --add-opens=java.base/java.net=ALL-UNNAMED
          # --add-opens=java.base/java.lang=ALL-UNNAMED
          # --add-opens=java.base/java.util=ALL-UNNAMED
          # --add-opens=java.naming/javax.naming.spi=ALL-UNNAMED
          # --add-opens=java.rmi/sun.rmi.transport.tcp=ALL-UNNAMED
          # --add-exports=java.base/sun.net.www.protocol.http=ALL-UNNAMED
          # --add-exports=java.base/sun.net.www.protocol.https=ALL-UNNAMED
          # --add-exports=java.base/sun.net.www.protocol.jar=ALL-UNNAMED
          # --add-exports=jdk.xml.dom/org.w3c.dom.html=ALL-UNNAMED
          # --add-exports=jdk.naming.rmi/com.sun.jndi.url.rmi=ALL-UNNAMED
          #
          # comment out this vmoption when using Java9+
          #
          -Djava.endorsed.dirs=lib/endorsed
        dest: "/home/{{ service }}/bin/nexus.vmoptions"
    - name: Set rc user
      copy:
        content: |
          run_as_user="nexus"
        dest: "/home/{{ service }}/bin/nexus.rc"
    become: yes
    become_user: "{{ service }}"
  - block:
    - name: Set systemd file
      copy:
        content: |
          [Unit]
          Description=nexus service
          After=network.target
  
          [Service]
          Type=forking
          LimitNOFILE=65536
          ExecStart=/home/{{ service }}/bin/nexus start
          ExecStop=/home/{{ service }}/bin/nexus stop
          User=nexus
          Restart=on-abort
  
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/nexus.service
    - name: Enable nexus
      ansible.builtin.systemd:
        name: nexus
        state: started
        enabled: true
    become: yes
    become_user: root