name: Install Nexus
tasks:
  - name: Download Nexus
    ansible.builtin.get_url:
      url: "https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/3/nexus-3.29.2-02-unix.tar.gz"
      dest: "./"
  - name: Extract nexus into /opt/nexus
    ansible.builtin.unarchive:
      src: nexus-3.29.2-02-unix.tar.gz
      dest: /opt/nexus
      owner: nexus
      group: nexus