name: Set server CRON
dependencies:
  - role: buri
  - role: env
vars:
  server_number:
tasks:
  - block:
    - name: Install Cron
      ansible.builtin.yum:
        name: cronie
        state: latest
    - name: Enable Cron
      ansible.builtin.systemd:
        name: crond
        state: started
        enabled: true
    become: yes
    become_user: root
  - block:
    - name: Set service cron file
      copy:
        content: |
          MAILTO=""
          PATH=/bin:/usr/bin:/usr/local/bin
          {{ server_number|int%3*10 }},{{ server_number|int%3*10+30 }} * * * * sudo yum update -y > /dev/null
          0 {{ 3+server_number|int }} * * 6 sudo reboot
          */6 * * * * ~/buri -t go -a buri -g no/cantara/gotools > /dev/null
          */6 * * * * ~/buri -t go -a nerthus2/probe -g no/cantara/gotools -r > /dev/null
        dest: ~/CRON
        mode: 0640
      register: cron
    - name: Remove cronjob from crontab scheduler
      shell: crontab -r
      ignore_errors: true
      when: cron is changed
    - name: Configure cronjob via crontab scheduler
      shell: crontab ~/CRON
      when: cron is changed
    - name: Start probe
      shell: cd ~ && ./buri -t go -a nerthus2/probe -g no/cantara/gotools -r