name: Setup OpenSearch
dependencies:
  - role: docker
  - role: service
vars:
  service:
  zone:
  tag: ":latest"
  service_in_docker: true
  webserver_port: 5601
tasks:
  - name: Create a OpenSearch dashboard container
    community.docker.docker_container:
      name: opensearch-dashboard
      image: "opensearchproject/opensearch-dashboards{{ tag }}"
      pull: true
      restart_policy: always
      ports:
        - 5601:5601
      expose:
        - 5601
      env:
        - "OPENSEARCH_HOSTS=[\"http://opensearch.{{ zone }}:9200\"]"
        - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards