name: Set reportServiceHealthToVisuale.properties
dependencies:
  - role: user
vars:
  service:
  port:
  env:
  visuale:
  service_tag:
  service_type:
  host:
tasks:
  - set_fact:
      visuale: "{{ visuale }}/{{ env }}/{{ service }}/{{ host }}?service_tag={{ service_tag }}&service_type={{ service_type }}"
  - block:
    - name: Create scripts directory if it does not exist
      ansible.builtin.file:
        path: "/home/{{ service }}/scripts"
        state: directory
        mode: '0755'
    - name: Set report properties
      copy:
        content: |
          healthUrl='http://localhost:{{ port }}/{{ service }}/health'
          reportToUrl1='{{ visuale }}'
          #reportToUrl2='{{ visuale }}'
        dest: "/home/{{ service }}/scripts/reportServiceHealthToVisuale.properties"
    become: yes
    become_user: "{{ service }}"