name: Add service
dependencies:
  - role: utf8
  - role: user
  - role: buri
  - role: service_cron
tasks:
  - block:
      - name: Install htop
        ansible.builtin.yum:
          name: htop
          state: latest
      - name: Install jq
        ansible.builtin.yum:
          name: jq
          state: latest
    become: yes
    become_user: root
