name: Add service User
dependencies:
  - role: user
vars:
  service:
tasks:
  - name: Check if buri exists
    stat:
      path: "/home/{{ service }}/scripts"
    become: yes
    become_user: "{{ service }}"
    register: scripts
  - block:
    - name: Download buri
      ansible.builtin.get_url:
        url: "https://mvnrepo.cantara.no/content/repositories/releases/no/cantara/gotools/buri/v{{ buri_base_version }}/buri-v{{ buri_base_version }}-{{ os }}-{{ arch }}"
        dest: "/home/{{ service }}/"
        mode: u+rwx
      register: buri_new
    - name: Create symbolic link for buri
      file:
        src: "{{ buri_new.dest }}"
        dest: "/home/{{ service }}/buri"
        state: link
    become: yes
    become_user: "{{ service }}"
    when: scripts.stat.exists == false