---
- name: Create Loadbalancer
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: ap-northeast-1
    default_actions:
      - Type: fixed-response
        FixedResponseConfig:
          ContentType: "text/plain"
          MessageBody: "404 Not Found"
          StatusCode: "404"
    rules:
    vpc_name:
    fqdn:
    loadbalancer_name:
  tasks:
    - amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ vpc_name }}"
      register: vpc
    - name: Display VPC
      debug:
        var: vpc
    - amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ vpc.vpcs[0].id }}"
      register: subnets
    - name: Display Subnets
      debug: var=subnets
    - name: Create loadbalancer security group
      ec2_group:
        name: "{{ loadbalancer_name }}-sg"
        description: "Security group for loadbalancer"
        vpc_id: "{{ vpc.vpcs[0].id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        state: present
      register: security_group
    - name: obtain ACM certificate
      community.aws.acm_certificate_info:
        region: "{{ region }}"
        domain_name: "{{ fqdn }}"
      register: cert
    - name: Create Application Load Balancer
      elb_application_lb:
        name: "{{ loadbalancer_name }}"
        state: present
        region: "{{ region }}"
        security_groups:
          - "{{ security_group.group_id }}"
        subnets: "{{ subnets.subnets | map(attribute='id') | list }}"
        ip_address_type: dualstack
        listeners:
          - Protocol: HTTP
            Port: 80
            DefaultActions:
              - Type: redirect
                RedirectConfig:
                  Protocol: HTTPS
                  Port: "443"
                  Host: "#{host}"
                  Path: "/#{path}"
                  Query: "#{query}"
                  StatusCode: "HTTP_301"
          - Protocol: HTTPS
            Port: 443
            DefaultActions: "{{ default_actions }}"
            Certificates:
              - CertificateArn: "{{ cert.certificates[0].certificate_arn }}"
            SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
            Rules: "{{ rules }}"