name: Set nexus credentials
vars:
  service:
  gradle_content: |
    # Display all warnings (e.g. deprecation details)
    org.gradle.warning.mode=all
    
    nexusUsername=redacted
    nexusPassword=redacted
tasks:
  - block:
    - name: Create gredle directory if it does not exist
      ansible.builtin.file:
        path: "/var/lib/{{ service }}/.gradle"
        state: directory
        mode: '0750'
    - name: Set gradle properties file
      copy:
        content: "{{ gradle_content }}"
        dest: "/var/lib/{{ service }}/.gradle/gradle.properties"
    become: yes
    become_user: "{{ service }}"