cidr_base: 10.96.0
vars:
  service_tag: SoftwareFactory
clusters:
  - name: jenkins
    number_of_nodes: 1
    os_name: Amazon Linux 2
    os_arch: x86_64
    instance_type: t3.xlarge
    services:
      - name: jenkins
        local: jenkins.yml
        webserver_port: 8080
      - name: mongodb
        local: mongodb.yml
    vars:
      mongo_host_port: 27777