name: Jenkins
service_type: H2A
health_type: jenkins
dependencies:
requirements:
  ram: 1GB
  disk: 5GB
  cpu: 1
  properties: .env
  not_cluster_able: true
  is_frontend: true
  roles:
    - jenkins
    - credentials
  services:
    - mongodb