---
- name: Create resources in Tokyo region
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: ap-northeast-1
    ami: ami-0bba69335379e17f8 #"ami-0bba69335379e17f8"
    instance_size: t3.small #t4g.nano #t3.small
    cidr_base: 10.100.0
    service: wamper
    system: cantara-lab
    zone: lab.cantara.infra
    security_group_rules: []
  tasks:
    - set_fact:
        vpc_cidr: "{{ cidr_base }}.0/24"
        subnets:
          - { name: "{{ system }}-subnet-1", az: "{{ region }}a", cidr: "{{ cidr_base }}.0/26" }
          - { name: "{{ system }}-subnet-2", az: "{{ region }}c", cidr: "{{ cidr_base }}.64/26" }
          - { name: "{{ system }}-subnet-3", az: "{{ region }}d", cidr: "{{ cidr_base }}.128/26" }
        instances:
          - { name: "{{ system }}-{{ service }}-1", ami: "{{ ami }}" }
          - { name: "{{ system }}-{{ service }}-2", ami: "{{ ami }}" }
          - { name: "{{ system }}-{{ service }}-3", ami: "{{ ami }}" }
        key_name: "{{ system }}-key"
        vpc_name: "{{ system }}-vpc"
        lb_name: "{{ system }}-lb"
        security_group_name: "{{ system }}-{{ service }}-sg"
        target_group_name: "{{ system }}-{{ service }}-tg"
    - set_fact:
        security_group_rules_base:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: all
            group_name: "{{ security_group_name }}"
    - name: Create key pair
      ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        key_type: "ed25519"
        state: present
      register: key_pair
    - name: check if key file exists
      stat:
        path: "../keys/{{ key_name }}.pem"
      register: keyfile
    - name: Copy private key to local machine
      copy:
        content: "{{ key_pair.key.private_key }}"
        dest: "../keys/{{ key_name }}.pem"
        mode: 0600
      when: keyfile.stat.exists == false
    - name: Create VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        ipv6_cidr: true
        region: "{{ region }}"
        state: present
      register: vpc
    - name: Ansible | Print ipv6
      debug:
        msg: "{{ vpc.vpc.ipv6_cidr_block_association_set[0].ipv6_cidr_block[:17] }}{{ index }}::/64"
      loop: "{{ subnets | flatten(levels=1) }}"
      loop_control:
        index_var: index
    - name: Associate subnet to the VPC
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ item.cidr }}"
        assign_instances_ipv6: true
        ipv6_cidr: "{{ vpc.vpc.ipv6_cidr_block_association_set[0].ipv6_cidr_block[:17] }}{{ index }}::/64"
        az: "{{ item.az }}"
        tags:
          Name: "{{ item.name }}"
      register: subnets
      loop: "{{ subnets | flatten(levels=1) }}"
      loop_control:
        index_var: index
    - name: Create ec2 vpc internet gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        state: present
      register: igw_result
    - name: Gather information about any VPC route table within VPC with ID vpc-abcdef00
      amazon.aws.ec2_vpc_route_table_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ vpc.vpc.id }}"
      register: route_info
    - name: Ansible | Print route info
      debug:
        msg: "{{ route_info }}"
    - name: Create gateway route table
      amazon.aws.ec2_vpc_route_table:
        region: "{{ region }}"
        vpc_id: "{{ vpc.vpc.id }}"
        lookup: id
        route_table_id: "{{ route_info.route_tables[0].id }}"
        tags:
          Name: Gateway route table
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_result.gateway_id }}"
          - dest: ::/0
            gateway_id: "{{ igw_result.gateway_id }}"
    - name: Ansible | Print security group rules
      debug:
        msg: "{{ security_group_rules_base + security_group_rules }}"
    - name: Create security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: "Security group for instances"
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        rules: "{{ security_group_rules_base + security_group_rules }}"
        state: present
      register: security_group
    - name: Create a private zone
      amazon.aws.route53_zone:
        zone: "{{ zone }}"
        vpc_id: "{{ vpc.vpc.id }}"
        vpc_region: "{{ region }}"
        comment: DNS for wamper lab cantara
    - name: Gather Facts to check if a similar instance is running
      ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ item.name }}"
      register: ec2_exists
      with_items: "{{ instances }}"
    - name: Display Details
      debug: var=ec2_exists
    - set_fact:
        ip_addresses_old: "{{ ec2_exists.results | selectattr('instances', 'defined') | map(attribute='instances') | flatten | selectattr('state.name','equalto','running') | map(attribute='private_ip_address') | list }}"
    - name: Route 53 A Record Update Before Launch
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        private_zone: true
        record: "{{ service }}.{{ zone }}"
        type: A
        ttl: 20
        value: "{{ ip_addresses_old }}"
        wait: yes
        overwrite: yes
      when: ip_addresses_old | count >= 1
    - name: Route 53 A Record Deleting Before Launch
      amazon.aws.route53:
        state: absent
        zone: "{{ zone }}"
        private_zone: true
        record: "{{ service }}.{{ zone }}"
        type: A
        ttl: 20
        wait: yes
        overwrite: yes
      when: ip_addresses_old | count == 0
    - name: Launch instances
      ec2_instance:
        key_name: "{{ key_name }}"
        security_group: "{{ security_group_name }}"
        count: 1
        instance_type: "{{ instance_size }}"
        image_id: "{{ item.ami }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnets.results[index].subnet.id }}"
        network:
          assign_public_ip: true
        volumes:
          - device_name: /dev/xvda
            ebs:
              volume_size: 20
              volume_type: "gp3"
        tags:
          Name: "{{ item.name }}"
        state: started
        wait: true
        user_data: |
          #!/bin/sh
          amazon-linux-extras enable ansible2
          yum install -y ansible > /dev/null
          ansible-galaxy collection install community.docker > /dev/null
          cd /home/ec2-user
          cat <<'EOF' > ./CRON
          MAILTO=""
          {{ index%3*10 }},{{ index%3*10+30 }} * * * * sudo yum update -y > /dev/null
          0 {{ 3+index }} * * 6 sudo reboot
          */6 * * * * ./buri -a nerthus2/probe/health -g no/cantara/gotools > /dev/null
          */5 * * * * ./nerthus2-probe-health -d 5m -r "https://visuale.cantara.no/api/status/example/{{ service | capitalize }}/{{ item.name }}?service_tag=EventServices&service_type=A2A" -h "http://localhost:2113" -t "es" > /dev/null &
          EOF
          chown ec2-user CRON
          chgrp ec2-user CRON

          sudo -u ec2-user crontab ./CRON

          yum install -y docker > /dev/null
          systemctl start docker
          systemctl enable docker
          addr=$(hostname -I | cut -f1 -d' ')
          docker run -d --restart=always --name eventstore -p 2113:2113 -p 1113:1113 -p 1112:1112 eventstore/eventstore:latest --insecure --cluster-size=3 --cluster-dns={{ service }}.{{ zone }} --int-ip=0.0.0.0 --int-host-advertise-as=$addr --ext-ip=0.0.0.0 --ext-host-advertise-as=$addr
          usermod -a -G docker ec2-user

          arci=$(uname -m)
          if [ "$arci" = "x86_64" ]; then
          arci="amd64"
          elif [ "$arci" = "aarch64" ]; then
          arci="arm64"
          fi;
          fname="buri-v0.7.0-$(uname | tr '[:upper:]' '[:lower:]')-$arci"
          curl --fail --show-error --silent -o "$fname" "https://mvnrepo.cantara.no/content/repositories/releases/no/cantara/gotools/buri/v0.7.0/$fname"
          ln -s "$fname" "buri"
          chmod +x "buri"
      register: instances
      async: 3600
      poll: 0
      with_items: "{{ instances }}"
      loop: "{{ instances | flatten(levels=1) }}"
      loop_control:
        index_var: index
      when:
        - ec2_exists.results[index].instances | count == 0 or ec2_exists.results[index].instances | selectattr('state.name','equalto','running') | list | count == 0
    - name: Wait for instances launch to finish
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: instances
      #register: instances
      retries: 500
      delay: 5
      until: instances.finished
      #until: instances.finished
      loop: "{{instances.results}}"
      when:
        - item.finished is defined
        - item.finished == 0
    - name: Display New Instances
      debug: var=instances
    - set_fact:
        ip_addresses_new: "{{ instances.results | selectattr('instances', 'defined') | map(attribute='instances') | flatten | map(attribute='private_ip_address') | list }}"
    - set_fact:
        ip_addresses: "{{ ip_addresses_new + ip_addresses_old }}"
    - name: Display IPs
      debug: var=ip_addresses
    - name: Route 53 A Record Update After Launch
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        private_zone: true
        record: "{{ service }}.{{ zone }}"
        type: A
        ttl: 20
        value: "{{ ip_addresses }}"
        wait: yes
        overwrite: yes
    - set_fact:
        instances_ids_old: "{{ ec2_exists.results | selectattr('instances', 'defined') | map(attribute='instances') | flatten | selectattr('state.name','equalto','running') | map(attribute='instance_id') | list }}"
        instances_ids_new: "{{ instances.results | selectattr('instances', 'defined') | map(attribute='instances') | flatten | selectattr('instance_id', 'defined') | map(attribute='instance_id') | list }}"
    - name: Display instance_ids_old
      debug:
        msg: "{{ instances_ids_old }}"
    - name: Display instance_ids_new
      debug:
        msg: "{{ instances_ids_new }}"