name: test
fqdn: "*.nerthusdev.cantara.dev"
os_name: Amazon Linux 2023
os_arch: arm64
instance_type: t4g.micro
visuale_host: visuale.nerthusdev.cantara.dev
nerthus_host: nerthus.nerthusdev.cantara.dev
vars:
  public_domain: dev.greps.dev
systems:
  - jenkins
  - nerthus
  - visuale
  - nexus
